# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Magento Meetup Austria
email: admin@matthias-zeis.com
description: >- # this means to ignore newlines until "baseurl:"
  Magento Meetup Austria: Hallo Magento-Fans! Steigen Sie bei uns ein uns besuchen Sie eines unserer Meetups.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mage-meetup.at" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mage_AT
github_username:  magento-meetup-austria
lang: de
google_analytics: UA-59207222-2
next_date: 01.02.2018
next_city: Wien

collections:
  meetups:
    output: true
    permalink: /:collection/:name

defaults:

  - scope:
      path: ""
      type: meetups
    values:
      layout: meetup

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
